### ISSUE TITLE
Request to include gpsdecode in the Hazard Mitigation Planning Toolkit for Electric Coops

### ISSUE THREAD

**Issue by invisibleroads** [beroset/gpsdecode#1]
We are assembling a toolkit to help electric coops plan upgrades. Can we include gpsdecode in the toolkit?

gpsdecode will be listed under the beroset user profile. If CrossCompute receives revenue, you will receive revenue share that is proportional to how often gpsdecode is used.

We are thinking of making a simple web-based tool that will let users try gpsdecode using different WAN addresses. How do you envision rural coops integrating gpsdecode into their meter reading analytics?

@kashfifahim

**Comment by beroset** [comment]
No, I'm not interested.
